# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metros_cuadrados', models.CharField(blank=True, max_length=250)),
                ('poligono', models.CharField(blank=True, max_length=250)),
                ('numero_parcela', models.CharField(blank=True, max_length=250)),
                ('autorizacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellidos', models.CharField(blank=True, max_length=250)),
                ('nif', models.CharField(blank=True, max_length=250)),
                ('domicilio', models.CharField(blank=True, max_length=250)),
                ('telefono_fijo', models.CharField(blank=True, max_length=250)),
                ('telefono_movil', models.CharField(blank=True, max_length=250)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectorTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='parcela',
            name='propietario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcels.Propietario'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='sector_trabajo',
            field=models.ManyToManyField(blank=True, to='parcels.SectorTrabajo'),
        ),
    ]
