# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcela',
            options={'ordering': ['-created'], 'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'ordering': ['-nombre'], 'verbose_name': 'Propietario', 'verbose_name_plural': 'Propietarios'},
        ),
        migrations.AlterModelOptions(
            name='sectortrabajo',
            options={'ordering': ['sector'], 'verbose_name': 'Sector Trabajo', 'verbose_name_plural': 'Sectores de Trabajo'},
        ),
    ]
