# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_auto_20180305_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameField(
            model_name='propietario',
            old_name='domicilio',
            new_name='calle',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='autorizacion',
        ),
        migrations.AddField(
            model_name='parcela',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='email',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='propietario',
            name='poblacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='parcela',
            name='estado',
            field=models.ManyToManyField(blank=True, to='parcels.Estado'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='proyecto',
            field=models.ManyToManyField(blank=True, to='parcels.Proyecto'),
        ),
    ]
