# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_auto_20180315_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcela',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='sector_trabajo',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='sector_trabajo',
            field=models.ManyToManyField(blank=True, to='parcels.SectorTrabajo'),
        ),
        migrations.AddField(
            model_name='sectortrabajo',
            name='parcela',
            field=models.ManyToManyField(blank=True, to='parcels.Parcela'),
        ),
    ]
