# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_auto_20180317_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='sector_trabajo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='parcels.SectorTrabajo'),
        ),
    ]
