# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_parcela_sector_trabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcela',
            name='sector_trabajo',
        ),
        migrations.AddField(
            model_name='parcela',
            name='sector_trabajo',
            field=models.ManyToManyField(blank=True, related_name='_parcela_sector_trabajo_+', to='parcels.SectorTrabajo'),
        ),
    ]
